### ISSUE TITLE
works on windows

### ISSUE THREAD

**Issue by ghost** [jdorfman/g20#2]
I have installed and tested g20 on Windows 10, everything runs well as expected. So I guess that g20 is truly cross-platform so shouldn't the readme be updated?
![screenshot 1](https://cloud.githubusercontent.com/assets/16728320/12373559/1754eca4-bc4b-11e5-90f1-72183c6c8a3e.png)

**Comment by jdorfman** [comment]
nice!  Want to create a PR?  I will do it just thought I'd ask first.  Thanks so much for reporting this, it is hard for me to find a Windows machine with Node installed.

**Comment by ghost** [comment]
@jdorfman sure I'll do a PR, thanks!

**Comment by ghost** [comment]
@jdorfman seems as if getting another green check on the readme is a difficult task for me, seems as if you'll have to do it

**Comment by jdorfman** [comment]
@mykhpl all good, thanks again for testing this!
