### ISSUE TITLE
clipboard enhancement

### ISSUE THREAD

**Issue by roccomuso** [jdorfman/g20#5]
Replace copy-past with [clipboardy](https://github.com/sindresorhus/clipboardy) that has binary fallbacks and doesn't require additional external dependencies.

**Comment by jdorfman** [comment]
@roccomuso will that fix `(node:49592) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'`?

**Comment by roccomuso** [comment]
Yeah I think so, this is not needed anymore `require('copy-paste').global()`

**Comment by jdorfman** [comment]
K thanks I will fix this asap

**Comment by jdorfman** [comment]
Done thanks, works a lot better!
